[package]
name = "wc_r"
version = "0.1.0"
authors = ["stuart"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
unicode-segmentation = "1.3.0"
rayon = "1.2.0"
itertools = "0.8.0"